### ISSUE TITLE
[Request] Add more items from sand:box

### ISSUE THREAD

**Issue by Jeweldation** [JMS55/sandbox#11]
This game should have more stuff and more options, like from [sand:box](https://play.google.com/store/apps/details?id=smellymoo.sand)

**Comment by JMS55** [comment]
Hi, I hope you are enjoying Sandbox!

At this time, I'm not planning to develop new features for Sandbox. The game will only receive bugfixes, and upgrading libraries as wgpu/pixels/freedestkop-sdk/etc have new releases.

That said, I would be happy to review PRs adding new particles/features, and provide any guidance needed in understanding the codebase. 

I've also gone ahead and enabled [github discussions](https://github.com/JMS55/sandbox/discussions/categories/ideas), so feel free to leave ideas there, as well as get feedback on potential features before implementing them.
