### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by koalefant** [JMS55/sandbox#4]
I am trying to build latest and get following error:
```
error: failed to get `imgui-wgpu` as a dependency of package `sandbox v1.1.0 (/home/admix/github/sandbox)`

Caused by:
  failed to load source for dependency `imgui-wgpu`

Caused by:
  Unable to update https://github.com/cwfitzgerald/imgui-wgpu-rs?branch=wgpu-update#6a9d7e31

Caused by:
  object not found - no match for id (6a9d7e315ada6fa9738b2e6f6cb69e0e3e4a9e4b); class=Odb (9); code=NotFound (-3)
```

**Comment by JMS55** [comment]
I've updated a bunch of dependencies and such on a local branch, I'm waiting for a new winit/winit-imgui-support release before I push it though. Didn't know master was broken, thanks for letting me know.

In the mean time, switch to using imgui-wgpu from crates.io.

**Comment by JMS55** [comment]
I pushed some of the dependency updates actually, master should build again now.
