### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by HexSleeves** [JMS55/sandbox#51]
I have been studying and building sand sims in my free time and wanted to ask if I could use your repository as inspiration and advice? Currently I am using other game engines to do the window management and ui, but would love to learn winnit for my own personal gain.

**Comment by JMS55** [comment]
Sandbox is open source under the AGPLv3 license (no commercial use, if you make any changes and distribute it beyond personal use then keep it open source, etc). Feel free to modify it and learn from it :)

That said, I wrote Sandbox a few years ago at this point. I haven't kept up maintaining it and updating it to the latest versions of winit/wgpu/etc, and the code quality isn't as good as it could be. There's definitely stuff I could have done better.

Hope you enjoy!
